USE GoVagas
GO

INSERT INTO Empresa(AnexarLogo,CargoArea,WebSite,NomeEmpresa,CNPJ,TipoEmpresa,DescricaoEmpresa,LocalizacaoEmpresa,EncontrouSenai,IdUsuario) VALUES
( NULL,'Gerente de projetos','https://www.demeo.com.br/','DE MEO COMERCIAL IMPORTADORA LTDA', '60.872.124/0004-31','Sociedade Empresária Limitada', 'Todas as lojas De Meo trabalham com uma grande linha de produtos atendendo os mais diversos segmentos do mercado.','RUA FLORENCIO DE ABREU, 271','Parceria',1),
( NULL,'Gerente de projetos','https://www.automatsmart.com/site/site/portugues','AUTOMATSMART TECH LTDA - ME', '24.809.668/0001-42','Sociedade Empresária Limitada ', 'Garantimos o melhor Desempenho Industrial com tecnologias inovadoras para aumentar a Eficiência e evitar perdas de Produtividade.','SENAI-SCS - RUA SANTO ANDRÉ, 680','Parceria',5),
( NULL,'Gerente de projetos','https://www.creditas.com/','CREDITAS SOLUÇÕES FINANCEIRAS LTDA', '17.770.708/0002-05','Sociedade Empresária Limitada', 'A Creditas é uma plataforma digital que atua como correspondente Bancário e Sociedade de Crédito Direto para facilitar o processo de contratação de empréstimos.','AV. ENGº LUIS CARLOS BERRINI, 105 - 12º AND','Parceria',6),
( NULL,'Gerente de projetos','https://www.spaceneedle.com.br/','SPACE NEEDLE TECNOLOGIA LTDA - EPP', '18.381.466/0001-40','Sociedade Empresária Limitada', 'Nosso propósito, valores, princípios e boas práticas são o resultado de mais de seis anos de experimentação e melhorias contínuas em todos os aspectos profissionais e pessoais.','ALAMEDA RIO NEGRO, 500, SALA 215A - ALPHAVILLE','Parceria',7);
--('','Gerente de projetos','http://aikensolutions.com.br/','AIKEN SOLUTIONS SERVIÇOS DE INFO LTDA', '','Sociedade Empresária Limitada', 'Aiken é o nome de um rio, justamente o fio condutor que pretendemos ser, levando nosso conhecimento e serviços a clientes para que cresçam e se fortaleçam. A TI é área fundamental em uma empresa, um órgão vital que requer atenção constante.','A. FRANCISCO MATARAZZO, 1752 CJ 420/421 - ÁGUA BRANCA','Parceria',5)
--('','Gerente de projetos','https://www.madeinweb.com.br/','MADEINWEB E MOBILE LTDA - ME', '09.557.985/0001-25','Sociedade Empresária Limitada', 'Desenvolver soluções web e mobile focadas em resultados para os clientes, propondo soluções criativas e inovadoras que agreguem valor e superem as expectativas','AV. PAULISTA, 1159','Parceria',6)
--('','Gerente de projetos','https://people-team.com/','PEOPLE TEAM LTDA', '04.831.457/0001-07','Sociedade Empresária Limitada', 'A People-Team é uma empresa de projetos turn key nas áreas de TI, Telecom, Engenharia Elétrica, Automação Industrial e Predial. Atuando desde 1993, na área de Automação, com o firme compromisso de prover soluções e servi-ços de qualidade, aliada a uma equipe capacitada continuamente para o desenvolvimento e implantação de sistemas completos com elevado grau de comprometimento com o cliente e seus objetivos estratégicos e operacionais.','RUA MIGUEL MENTEM, 204 - V. GUILHERME','Parceria',7)
--('','Gerente de projetos','http://www.cultura.sp.gov.br/','SECRETARIA MUNICIPAL DA CULTURA - SP', '30.250.600/0001-79','Empresas de médio e grande porte', 'A Secretaria Especial da Cultura é o órgão do Ministério do Turismo responsável pela formação de políticas, programas e projetos de promoção da cidadania por meio da cultura.','AV. SÃO JOÃO. 473 - 9º ANDAR','Parceria',8)
--('','Gerente de projetos','https://www.cps.sp.gov.br/tag/etec-dra-maria-augusta-saraiva/','CENTRO PAULA SOUZA ETEC DRA MARIA AUGUSTA SARAIVA', '','Empresas de médio e grande porte', '','RUA GUAIANASES, 1385 - CAMPOS ELISEOS','Parceria',9)
--('','Gerente de projetos','http://agricol.com.br/','AGRICOL DIESEL LTDA', '51.193.118/0001-14','Sociedade Empresária Limitada', 'A Agricol é um Posto de Serviço Autorizado Mercedes-Benz que desde 1979 tem mantido como foco principal a satisfação total de seus clientes, oferecendo produtos e serviços com os melhores preços e condições de pagamento com a qualidade Mercedes-Benz. ','RUA ALMIRANTE PESTANA, 76 - VILA MONUMENTO','Parceria',10);

SELECT * FROM Empresa;
